# subconverter é…ç½®æ–‡ä»¶ (ä¿®æ­£ç‰ˆ)
version = 1

[custom]
api_mode = false
api_access_token = "password"
default_url = []
enable_insert = true
insert_url = [""]
prepend_insert_url = true
exclude_remarks = ["(åˆ°æœŸ|å‰©ä½™æµé‡|æ—¶é—´|å®˜ç½‘|äº§å“)"]

default_external_config = "https://raw.githubusercontent.com/double-tu/sub-rules/master/subconverter_config.ini"
base_path = "base"

clash_rule_base = "https://raw.githubusercontent.com/double-tu/sub-rules/master/clash/template_config.yaml"
surge_rule_base = "base/all_base.tpl"
surfboard_rule_base = "base/all_base.tpl"
mellow_rule_base = "base/all_base.tpl"
quan_rule_base = "base/all_base.tpl"
quanx_rule_base = "https://raw.githubusercontent.com/double-tu/sub-rules/master/quanx/template_config.conf"
loon_rule_base = "https://raw.githubusercontent.com/double-tu/sub-rules/master/loon/template_config.conf"
sssub_rule_base = "base/all_base.tpl"
singbox_rule_base = "base/all_base.tpl"

proxy_config = "SYSTEM"
proxy_ruleset = "SYSTEM"
proxy_subscription = "NONE"
append_proxy_type = false
reload_conf_on_request = false

# ç”¨æˆ·ä¿¡æ¯æå–è§„åˆ™
[[userinfo.stream_rule]]
match = '^å‰©ä½™æµé‡ï¼š(.*?)\|æ€»æµé‡ï¼š(.*)$'
replace = 'total=$2&left=$1'

[[userinfo.stream_rule]]
match = '^å‰©ä½™æµé‡ï¼š(.*?) (.*)$'
replace = 'total=$1&left=$2'

[[userinfo.stream_rule]]
match = '^Bandwidth: (.*?)/(.*)$'
replace = 'used=$1&total=$2'

[[userinfo.stream_rule]]
match = '^\\[.*?\\]å‰©ä½™(.*?)@(?:.*)$'
replace = 'total=$1'

[[userinfo.stream_rule]]
match = '^.*?æµé‡:(.*?) å‰©:(?:.*)$'
replace = 'total=$1'

[[userinfo.time_rule]]
match = '^[åˆ°è¿‡]æœŸæ—¶é—´ï¼š(\\d+)-(\\d+)-(\\d+) (\\d+):(\\d+):(\\d+)$'
replace = '$1:$2:$3:$4:$5:$6'

[[userinfo.time_rule]]
match = '^[åˆ°è¿‡]æœŸï¼š(\\d+)-(\\d+)-(\\d+) (\\d+):(\\d+):(\\d+)$'
replace = '$1:$2:$3:$4:$5:$6'

[[userinfo.time_rule]]
match = '^[åˆ°è¿‡]æœŸæ—¶é—´(:|ï¼š)(\\d+)-(\\d+)-(\\d+)$'
replace = '$1:$2:$3:0:0:0'

[[userinfo.time_rule]]
match = '^[åˆ°è¿‡]æœŸ(:|ï¼š)(\\d+)-(\\d+)-(\\d+)$'
replace = '$1:$2:$3:0:0:0'

[[userinfo.time_rule]]
match = '^Smart Access expire: (\\d+)/(\\d+)/(\\d+)$'
replace = '$1:$2:$3:0:0:0'

[[userinfo.time_rule]]
match = '^.*?æµé‡:(?:.*?) å‰©:(.*)$'
replace = 'left=$1d'

[node_pref]
sort_flag = false
filter_deprecated_nodes = false
append_sub_userinfo = true
clash_use_new_field_name = true
clash_proxies_style = "flow"
clash_proxy_groups_style = "block"
singbox_add_clash_modes = true

# èŠ‚ç‚¹é‡å‘½åè§„åˆ™ (ä¿®æ­£ç‰ˆ)
[[node_pref.rename_node]]
match = '!!GROUP=æ¸¡å£!!(^.+$)'
replace = '[æœº][æ¸¡å£] - $1'

[[node_pref.rename_node]]
match = '!!GROUP=element!!(^.+$)'
replace = '[æœº][element] - $1'

[[node_pref.rename_node]]
match = '!!GROUP=é£é¸Ÿ!!(^.+$)'
replace = '[æœº][é£é¸Ÿ] - $1'

[[node_pref.rename_node]]
match = '!!GROUP=èŠ±äº‘!!(^.+$)'
replace = '[æœº][èŠ±äº‘] - $1'

[[node_pref.rename_node]]
match = '!!GROUP=å®¶å®½!!(^.+$)'
replace = '[å®¶] - $1'

[[node_pref.rename_node]]
match = '!!GROUP=è½åœ°!!(^.+$)'
replace = '[è½] - $1'

[managed_config]
write_managed_config = true
managed_config_prefix = "http://127.0.0.1:25500"
config_update_interval = 86400
config_update_strict = false
quanx_device_id = ""

[surge_external_proxy]
resolve_hostname = true

[emojis]
add_emoji = false
remove_old_emoji = true

# è‡ªå®šä¹‰åˆ†ç»„
[[custom_groups]]
name = "âœˆï¸ èµ·é£å‡ºå›½"
type = "select"
rule = ["[]âœ‹ğŸ» æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ”— é“¾-é¦™æ¸¯", "[]ğŸ”— é“¾-å°æ¹¾", "[]ğŸ”— é“¾-æ—¥æœ¬", "[]ğŸ”— é“¾-æ–°åŠ å¡", "[]ğŸ”— é“¾-ç¾å›½", "[]ğŸ”° å›½å†…ç›´è¿"]

[[custom_groups]]
name = "âœ‹ğŸ» æ‰‹åŠ¨åˆ‡æ¢"
type = "select"
rule = ["[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ§º å…¶ä»–èŠ‚ç‚¹"]

[[custom_groups]]
name = "ğŸ”° å›½å†…ç›´è¿"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "â›”ï¸ å¹¿å‘Šæ‹¦æˆª"
type = "select"
rule = ["[]REJECT"]

[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]âœˆï¸ èµ·é£å‡ºå›½", "[]âœ‹ğŸ» æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ”° å›½å†…ç›´è¿", "[]ğŸ”— é“¾-é¦™æ¸¯", "[]ğŸ”— é“¾-å°æ¹¾", "[]ğŸ”— é“¾-æ—¥æœ¬", "[]ğŸ”— é“¾-ç¾å›½", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ§º å…¶ä»–èŠ‚ç‚¹"]

# å®¶å®½è½åœ°æ‰‹é€‰
[[custom_groups]]
name = "ğŸ  å®¶-é¦™æ¸¯è½åœ°"
type = "select"
rule = ['(?=.*(\[å®¶\]|\[è½\]))(?=.*é¦™æ¸¯).*']

[[custom_groups]]
name = "ğŸ  å®¶-å°æ¹¾è½åœ°"
type = "select"
rule = ['(?=.*(\[å®¶\]|\[è½\]))(?=.*å°æ¹¾).*']

[[custom_groups]]
name = "ğŸ  å®¶-æ—¥æœ¬è½åœ°"
type = "select"
rule = ['(?=.*(\[å®¶\]|\[è½\]))(?=.*æ—¥æœ¬).*']

[[custom_groups]]
name = "ğŸ  å®¶-æ–°åŠ å¡è½åœ°"
type = "select"
rule = ['(?=.*(\[å®¶\]|\[è½\]))(?=.*æ–°åŠ å¡).*']

[[custom_groups]]
name = "ğŸ  å®¶-ç¾å›½è½åœ°"
type = "select"
rule = ['(?=.*(\[å®¶\]|\[è½\]))(?=.*ç¾å›½).*']

# ä¸šåŠ¡ç­–ç•¥ç»„
[[custom_groups]]
name = "ğŸ¬ å›½å¤–åª’ä½“"
type = "select"
rule = ["[]âœˆï¸ èµ·é£å‡ºå›½", "[]ğŸ”— é“¾-é¦™æ¸¯", "[]ğŸ”— é“¾-å°æ¹¾", "[]ğŸ”— é“¾-æ—¥æœ¬", "[]ğŸ”— é“¾-æ–°åŠ å¡", "[]ğŸ”— é“¾-ç¾å›½", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ§º å…¶ä»–èŠ‚ç‚¹"]

[[custom_groups]]
name = "ğŸ¤– ChatGPT"
type = "select"
rule = ["[]âœˆï¸ èµ·é£å‡ºå›½", "[]ğŸ”— é“¾-é¦™æ¸¯", "[]ğŸ”— é“¾-å°æ¹¾", "[]ğŸ”— é“¾-æ—¥æœ¬", "[]ğŸ”— é“¾-æ–°åŠ å¡", "[]ğŸ”— é“¾-ç¾å›½", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ§º å…¶ä»–èŠ‚ç‚¹"]

[[custom_groups]]
name = "ğŸ¦ Netflix"
type = "select"
rule = ["[]âœˆï¸ èµ·é£å‡ºå›½", "[]ğŸ”— é“¾-é¦™æ¸¯", "[]ğŸ”— é“¾-å°æ¹¾", "[]ğŸ”— é“¾-æ—¥æœ¬", "[]ğŸ”— é“¾-æ–°åŠ å¡", "[]ğŸ”— é“¾-ç¾å›½", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ§º å…¶ä»–èŠ‚ç‚¹"]

[[custom_groups]]
name = "ğŸ…³ Disney+"
type = "select"
rule = ["[]âœˆï¸ èµ·é£å‡ºå›½", "[]ğŸ”— é“¾-é¦™æ¸¯", "[]ğŸ”— é“¾-å°æ¹¾", "[]ğŸ”— é“¾-æ—¥æœ¬", "[]ğŸ”— é“¾-æ–°åŠ å¡", "[]ğŸ”— é“¾-ç¾å›½", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ§º å…¶ä»–èŠ‚ç‚¹"]

[[custom_groups]]
name = "â„¢ï¸éé€šç”¨ç½‘ç»œ"
type = "select"
rule = ["[]âœˆï¸ èµ·é£å‡ºå›½", "[]ğŸ”— é“¾-é¦™æ¸¯", "[]ğŸ”— é“¾-å°æ¹¾", "[]ğŸ”— é“¾-æ—¥æœ¬", "[]ğŸ”— é“¾-æ–°åŠ å¡", "[]ğŸ”— é“¾-ç¾å›½", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ§º å…¶ä»–èŠ‚ç‚¹"]

[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = ["[]ğŸ”° å›½å†…ç›´è¿", "[]âœˆï¸ èµ·é£å‡ºå›½"]

[[custom_groups]]
name = "ğŸª‚ TikTok"
type = "select"
rule = ["[]âœˆï¸ èµ·é£å‡ºå›½", "[]ğŸ”— é“¾-é¦™æ¸¯", "[]ğŸ”— é“¾-å°æ¹¾", "[]ğŸ”— é“¾-æ—¥æœ¬", "[]ğŸ”— é“¾-æ–°åŠ å¡", "[]ğŸ”— é“¾-ç¾å›½", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ§º å…¶ä»–èŠ‚ç‚¹"]
[[custom_groups]]
name = "ğŸ¬ HBO"
type = "select"
rule = ["[]âœˆï¸ èµ·é£å‡ºå›½", "[]ğŸ”— é“¾-é¦™æ¸¯", "[]ğŸ”— é“¾-å°æ¹¾", "[]ğŸ”— é“¾-æ—¥æœ¬", "[]ğŸ”— é“¾-æ–°åŠ å¡", "[]ğŸ”— é“¾-ç¾å›½", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ§º å…¶ä»–èŠ‚ç‚¹"]
[[custom_groups]]
name = "ğŸ‘Œ Crypto"
type = "select"
rule = ["[]âœˆï¸ èµ·é£å‡ºå›½", "[]ğŸ”— é“¾-é¦™æ¸¯", "[]ğŸ”— é“¾-å°æ¹¾", "[]ğŸ”— é“¾-æ—¥æœ¬", "[]ğŸ”— é“¾-æ–°åŠ å¡", "[]ğŸ”— é“¾-ç¾å›½", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ§º å…¶ä»–èŠ‚ç‚¹"]

[[custom_groups]]
name = "ğŸ® æ¸¸æˆèŠ‚ç‚¹"
type = "select"
rule = ["[]ğŸ”° å›½å†…ç›´è¿", "[]âœˆï¸ èµ·é£å‡ºå›½", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ§º å…¶ä»–èŠ‚ç‚¹"]

[[custom_groups]]
name = "ğŸ–¥ï¸ SSHèŠ‚ç‚¹"
type = "select"
rule = ["[]ğŸ”° å›½å†…ç›´è¿", "[]âœˆï¸ èµ·é£å‡ºå›½", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ§º å…¶ä»–èŠ‚ç‚¹"]

# åœ°åŒºèŠ‚ç‚¹åˆ†ç»„
[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
type = "select"
rule = ['(?=.*(é¦™æ¸¯|æ¸¯|(?i)HK|(?i)Hong)).*']

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹"
type = "select"
rule = ['(?=.*(æ–°åŠ å¡|å¡|æ–°|ç‹®åŸ|(?i)SG|(?i)Singapore)).*']

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹"
type = "select"
rule = ['(?=.*(å°æ¹¾|å°|æ¹¾|å°ç£|(?i)TW|(?i)Taiwan)).*']

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
type = "select"
rule = ['(?=.*(æ—¥æœ¬|æ—¥|(?i)JP|(?i)Japan)).*']

[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹"
type = "select"
rule = ['(?=.*(ç¾å›½|ç¾|ç¾åœ‹|(?i)US|(?i)States|(?i)American)).*']

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹"
type = "select"
rule = ['(?=.*(éŸ©å›½|éŸ©|éŸ“åœ‹|å—æœé²œ|(?i)KR|(?i)Korean)).*']

[[custom_groups]]
name = "ğŸ§º å…¶ä»–èŠ‚ç‚¹"
type = "select"
rule = ['^(?!.*(?:è¿‡æœŸ|åˆ°æœŸ|å‰©ä½™|æ—¶é—´|æµé‡|æ´»åŠ¨|ä¼˜æƒ |é¦™æ¸¯|æ¸¯|å°æ¹¾|å°|æ¹¾|å°ç£|æ—¥æœ¬|æ—¥|ç¾å›½|ç¾|ç¾åœ‹|éŸ©å›½|éŸ©|éŸ“åœ‹|å—æœé²œ|æ–°åŠ å¡|å¡|æ–°|ç‹®åŸ|(?i:expire|expiry|expiration|due|remain|remaining|left|time|data|traffic|usage|hk|hong kong|sg|singapore|tw|taiwan|jp|japan|us|states|american|kr|korean))).*$']

# æœºåœºè´Ÿè½½å‡è¡¡
[[custom_groups]]
name = "âš–ï¸ æœº-é¦™æ¸¯è´Ÿè½½"
type = "load-balance"
rule = ['(?=.*\[æœº\])(?=.*é¦™æ¸¯).*']
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 3

[[custom_groups]]
name = "âš–ï¸ æœº-æ—¥æœ¬è´Ÿè½½"
type = "load-balance"
rule = ['(?=.*\[æœº\])(?=.*æ—¥æœ¬).*']
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 3

[[custom_groups]]
name = "âš–ï¸ æœº-å°æ¹¾è´Ÿè½½"
type = "load-balance"
rule = ['(?=.*\[æœº\])(?=.*å°æ¹¾).*']
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 3

[[custom_groups]]
name = "âš–ï¸ æœº-æ–°åŠ å¡è´Ÿè½½"
type = "load-balance"
rule = ['(?=.*\[æœº\])(?=.*æ–°åŠ å¡).*']
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 3

[[custom_groups]]
name = "âš–ï¸ æœº-ç¾å›½è´Ÿè½½"
type = "load-balance"
rule = ['(?=.*\[æœº\])(?=.*ç¾å›½).*']
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 3

[[custom_groups]]
name = "âš–ï¸ è´Ÿè½½å‡è¡¡ - æ–°æ¸¯æ—¥å°ä¸“çº¿"
type = "load-balance"
rule = ['(?i)^(?=.*((?i)HK|Hong Kong|é¦™æ¸¯|æ¸¯|(?i)SG|Singapore|æ–°åŠ å¡|å¡|ç‹®åŸ|(?i)JP|Japan|æ—¥æœ¬|å°æ¹¾|(?i)TW|(?i)Taiwan))(?=.*(iepl|ä¸“çº¿)).*$']
strategy = "consistent-hashing"
url = "http://www.gstatic.com/generate_204"
interval = 120
tolerance = 3

[[custom_groups]]
name = "âš–ï¸ è´Ÿè½½å‡è¡¡ - ç¾å›½ä¸“çº¿"
type = "load-balance"
rule = ['(?i)^(?=.*((?i)us|ç¾å›½|ç¾))(?=.*(iepl|ä¸“çº¿)).*$']
strategy = "consistent-hashing"
url = "http://www.gstatic.com/generate_204"
interval = 120
tolerance = 3

# é“¾å¼ä¸­ç»§
[[custom_groups]]
name = "ğŸ”— é“¾-é¦™æ¸¯"
type = "relay"
rule = ["[]âš–ï¸ æœº-é¦™æ¸¯è´Ÿè½½", "[]ğŸ  å®¶-é¦™æ¸¯è½åœ°"]

[[custom_groups]]
name = "ğŸ”— é“¾-å°æ¹¾"
type = "relay"
rule = ["[]âš–ï¸ æœº-å°æ¹¾è´Ÿè½½", "[]ğŸ  å®¶-å°æ¹¾è½åœ°"]

[[custom_groups]]
name = "ğŸ”— é“¾-æ—¥æœ¬"
type = "relay"
rule = ["[]âš–ï¸ æœº-æ—¥æœ¬è´Ÿè½½", "[]ğŸ  å®¶-æ—¥æœ¬è½åœ°"]

[[custom_groups]]
name = "ğŸ”— é“¾-æ–°åŠ å¡"
type = "relay"
rule = ["[]âš–ï¸ æœº-æ–°åŠ å¡è´Ÿè½½", "[]ğŸ  å®¶-æ–°åŠ å¡è½åœ°"]

[[custom_groups]]
name = "ğŸ”— é“¾-ç¾å›½"
type = "relay"
rule = ["[]âš–ï¸ æœº-ç¾å›½è´Ÿè½½", "[]ğŸ  å®¶-ç¾å›½è½åœ°"]

[ruleset]
enabled = true
overwrite_original_rules = false
update_ruleset_on_request = false

# è§„åˆ™é›†å®šä¹‰ (ä¿®æ­£ç‰ˆ)
[[rulesets]]
group = "ğŸ”° å›½å†…ç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]MATCH"

[template]
template_path = ""

[[template.globals]]
key = "clash.http_port"
value = "7890"

[[template.globals]]
key = "clash.socks_port"
value = "7891"

[[template.globals]]
key = "clash.allow_lan"
value = "true"

[[template.globals]]
key = "clash.log_level"
value = "info"

[[template.globals]]
key = "clash.external_controller"
value = "127.0.0.1:9090"

[[template.globals]]
key = "singbox.allow_lan"
value = "true"

[[template.globals]]
key = "singbox.mixed_port"
value = "2080"

[[aliases]]
uri = "/v"
target = "/version"

[[aliases]]
uri = "/clash"
target = "/sub?target=clash"

[[aliases]]
uri = "/clashr"
target = "/sub?target=clashr"

[[aliases]]
uri = "/surge"
target = "/sub?target=surge"

[[aliases]]
uri = "/quan"
target = "/sub?target=quan"

[[aliases]]
uri = "/quanx"
target = "/sub?target=quanx"

[[aliases]]
uri = "/mellow"
target = "/sub?target=mellow"

[[aliases]]
uri = "/surfboard"
target = "/sub?target=surfboard"

[[aliases]]
uri = "/loon"
target = "/sub?target=loon"

[[aliases]]
uri = "/ss"
target = "/sub?target=ss"

[[aliases]]
uri = "/ssd"
target = "/sub?target=ssd"

[[aliases]]
uri = "/sssub"
target = "/sub?target=sssub"

[[aliases]]
uri = "/ssr"
target = "/sub?target=ssr"

[[aliases]]
uri = "/v2ray"
target = "/sub?target=v2ray"

[[aliases]]
uri = "/trojan"
target = "/sub?target=trojan"

[server]
listen = "0.0.0.0"
port = 25500
serve_file_root = ""

[advanced]
log_level = "info"
print_debug_info = false
max_pending_connections = 10240
max_concurrent_threads = 2
max_allowed_rulesets = 0
max_allowed_rules = 0
max_allowed_download_size = 0
enable_cache = false
cache_subscription = 60
cache_config = 300
cache_ruleset = 216000
script_clean_context = true
async_fetch_ruleset = false
skip_failed_links = false
